### ISSUE TITLE
Double select on bullet stops slider.

### ISSUE THREAD

**Issue by nikhil8krishnan** [julianhandl/mostslider#4]
when we click the same pager(butllet navigation) twice the slider stopped sliding .what the reason ?

**Comment by julianhandl** [comment]
You are right. I will check this issue. Thank you for testing and stay tuned!

**Comment by nikhil8krishnan** [comment]
@julianhandl plz fix the bug ,im waiting for your reply..I would glad to you if the bug is fixed.thanks for your reply..

**Comment by julianhandl** [comment]
@nikhil8krishnan Should be fixed by sunday at the latest. Will inform you through this issue.

**Comment by nikhil8krishnan** [comment]
is there possible for a temporary solution?

**Comment by nikhil8krishnan** [comment]
i don't know how to fix individually if you solved the small issue I'm very thankfully to you

**Comment by julianhandl** [comment]
Bug is fixed. @nikhil8krishnan checkout the master branch.

**Comment by nikhil8krishnan** [comment]
thank you..it working well (y)....this is a responsive slider so the touch devices need to more comfortable for sliding interaction, would you please add gestural  touch  for touch devices..it will get you more appreciation .

**Comment by julianhandl** [comment]
Yes I know. I'm planing to do plenty of rework and make it much more mobile friendly.

**Comment by nikhil8krishnan** [comment]
well..nice work..congs
